spring:
  application:
    name: policy-service

  profiles:
    active: local



#spring:
#  application:
#    name: rule-service
#
#  config:
#    import: optional:configserver:http://config-service:8888
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-discovery:8761/eureka/
