server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/departments/**, /api/roles/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/oauth2/**

        - id: rule-service
          uri: lb://rule-service
          predicates:
            - Path=/api/rules/**, /api/policies/**, /api/variables/**, /api/parameters/**
          filters:
            - RemoveRequestHeader=Cookie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



# default
#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
#      routes:
#
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/users/**, /api/departments/**, /api/roles/**
#          filters:
#            - RemoveRequestHeader=Cookie
#
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**, /api/oauth2/**
#
#        - id: rule-service
#          uri: lb://rule-service
#          predicates:
#            - Path=/api/rules/**, /api/policies/**, /api/variables/**, /api/parameters/**
#          filters:
#            - RemoveRequestHeader=Cookie
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-discovery:8761/eureka/
